// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeLaA9pcCPzXAO0G2AMmYPbOiRItpNCTY',
    appId: '1:478061180849:web:d8eaf7ebdbda7630952f90',
    messagingSenderId: '478061180849',
    projectId: 'fir-4013c',
    authDomain: 'fir-4013c.firebaseapp.com',
    storageBucket: 'fir-4013c.appspot.com',
    measurementId: 'G-71BD7742TT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtvkp-nOxvWflw5mtNpxy1_JlE_NYWEbo',
    appId: '1:478061180849:android:4be373204d730e61952f90',
    messagingSenderId: '478061180849',
    projectId: 'fir-4013c',
    storageBucket: 'fir-4013c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvVTr4fN1C748rHOI4e1purqt29kEpg98',
    appId: '1:478061180849:ios:6e382c03e882831c952f90',
    messagingSenderId: '478061180849',
    projectId: 'fir-4013c',
    storageBucket: 'fir-4013c.appspot.com',
    iosBundleId: 'com.example.events',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvVTr4fN1C748rHOI4e1purqt29kEpg98',
    appId: '1:478061180849:ios:6e382c03e882831c952f90',
    messagingSenderId: '478061180849',
    projectId: 'fir-4013c',
    storageBucket: 'fir-4013c.appspot.com',
    iosBundleId: 'com.example.events',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeLaA9pcCPzXAO0G2AMmYPbOiRItpNCTY',
    appId: '1:478061180849:web:89b10cb4a20ede71952f90',
    messagingSenderId: '478061180849',
    projectId: 'fir-4013c',
    authDomain: 'fir-4013c.firebaseapp.com',
    storageBucket: 'fir-4013c.appspot.com',
    measurementId: 'G-3MBGPBCJ9H',
  );
}
